fix: Require OS version
The underlying gcloud commands require the version to be provided,
however the variable didn't:
```
ERROR: (gcloud.beta.compute.instances.ops-agents.policies.create) argument --os-types: Key [version] required in dict arg but not provided
```